### ISSUE TITLE
Strange Error in Aggregation with Jongo1.2

### ISSUE THREAD

**Issue by yairbr** [bguerout/jongo#284]
I am using the aggregation framework in order to retrieve an inner object of an mongo object.

this is my query :
List<InnerData> lst = lists.aggregate(matchQuery.toString()).and(unwindQuery.toString()).and(projectionQuery.toString()).as(InnerData.class);

 Thats the error i get- 
> Error:(177, 52) java: incompatible types: no instance(s) of type variable(s) T exist so that org.jongo.Aggregate.ResultsIterator<T> conforms to org.jongo.MongoCursor<main.java.DataTypes.InnerData>

The query works fine in Jongo 1.1, but when I write it with Jongo 1.2 i get an error the InnerData is incompatible type of T.

My drivers version is 3.0.0
thanks

**Comment by bguerout** [comment]
Hello can you try to reproduce this behaviour with the lastest Jongo version ?

**This version must be considered as a SNAPSHOT of future 1.3 release**
```xml
<dependencies>
  <dependency>
    <groupId>org.jongo</groupId>
    <artifactId>jongo</artifactId>
    <version>1.3-early-20151113-0140</version>
  </dependency>
</dependencies>
...
<repositories>
    <repository>
       <id>cloudbees-jongo-early-release</id>
        <url>http://repository-jongo.forge.cloudbees.com/release</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by haraldrombaut** [comment]
1.3-early-20151113-0140 is not available in the repository (1.3-early-20150728-0456 is the last version)

**Comment by singhularity** [comment]
Hi,
I'm trying to perform a simple aggregation using Jongo and I run into a similar issue where it does not accept  XYZ.class as argument in "as". Seems to work fine with find(). I don't see the issue with 1.1

**Comment by bguerout** [comment]
I've created a new early release but the previous one seems good to me.
Have you added the cloudbees-jongo-early-release repository

**This version must be considered as a SNAPSHOT of future 1.3 release**
```xml
<dependencies>
  <dependency>
    <groupId>org.jongo</groupId>
    <artifactId>jongo</artifactId>
    <version>1.3-early-20160303-1446</version>
  </dependency>
</dependencies>
...
<repositories>
    <repository>
       <id>cloudbees-jongo-early-release</id>
        <url>http://repository-jongo.forge.cloudbees.com/release</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by ctrimble** [comment]
@bguerout I tried to reproduce this against master and could not.  Unless someone provides a PR with a failing test case, I don't think this issue should hold up a 1.3 release.

**Comment by bguerout** [comment]
Tanks i'm going to test it against 1.2
