### ISSUE TITLE
jongo 1.2 incompatible with mongo-java-driver 2.11.4

### ISSUE THREAD

**Issue by gdelafosse** [bguerout/jongo#261]
Hello
I'm trying to use jongo 1.2 and mongo-java-driver 2.11.4.
According to your website, jongo 1.2 should work with mongo-java-driver 2.11.4+.

But I have this exception while running my tests :
java.lang.NoSuchMethodError: org.jongo.bson.BsonDBObject.getBytes()[B
	at org.jongo.bson.BsonDBObject.toByteArray(BsonDBObject.java:30)
	at org.jongo.marshall.jackson.JacksonEngine.unmarshall(JacksonEngine.java:42)
	at org.jongo.ResultHandlerFactory$UnmarshallingResultHandler.map(ResultHandlerFactory.java:43)
	at org.jongo.FindOne.map(FindOne.java:51)
	at org.jongo.FindOne.as(FindOne.java:46)
	
It works only if we use mongo-java-driver 2.12.+ or 2.13.+.
In an OSGI container, because of the "Import-Package" in MANIFEST file it won't work if mongo-java driver is not between those versions.
Could you update your website?

**Comment by bguerout** [comment]
Thanks
